name: pylint and build
on:
  workflow_dispatch: {}

jobs:
  build: 
    name: pylint_check
#     if: always()
    runs-on: ubuntu-18.04
    steps:
     - name: code checkout
       uses: actions/checkout@v1
     - name: python setup
       uses: actions/setup-python@v1
#        run: | 
#            python -m pip install --upgrade pip
#            pip install pylint
#            pylint *.py
#      - name: printi varaibles
#        run: echo "${{ toJson(github) }}"
     - name: Running lintering
#        uses: pyrunit/pylint-action@v1.0.0
       uses: cclauss/GitHub-Action-for-pylint@master
       with:
#          source: /home/runner/work/python-helloworld/python-helloworld/
         useConda: true
         args: "pip install . ; pylint **/*.py"

#@Nandak99
 
#        run: cd helloworld && python main.py
#      - name: Python Pylin GitHub Action
#        uses: fylein/python-pylint-github-action@v1
#        with:
#          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc ./
     - name: Send mail
       if: always()
       uses: dawidd6/action-send-mail@v3
       with:
    # Specify connection via URL (replaces server_address, server_port, secure,
    # username and password)
    #
    # Format:
    #
    #  * smtp://user:password@server:port
    #  * smtp+starttls://user:password@server:port
#         connection_url: smtp://techdevops001@gail.com:tvkgsyzzoonbepye@smtp.gmail.com:465
        connection_url: smtp://kishorenanda99@outlook.com:mstbarbblxuhxdqy@smtp.office365.com:465
    # Required mail server address if not connection_url:
        server_address: smtp.office365.com
    # Server port, default 25:
        server_port: 465
    # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
    # Optional (recommended): mail server username:
        username: kishorenanda99@outlook.com
    # Optional (recommended) mail server password:
        password: mstbarbblxuhxdqy
    # Required mail subject:
        subject:  ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
    # Required recipients' addresses:
        to: shyam.cbse@gmail.com
    # Required sender full name (address can be skipped):
        from: Radha-Collegue # <user@example.com>
    # Optional plain body:
        body:  ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
        ignore_cert: true
    
