name: pylint and build
on:
  workflow_dispatch: {}

jobs:
  build: 
    name: pylint_check
    runs-on: ubuntu-18.04
    steps:
     - name: code checkout
       uses: actions/checkout@v1
     - name: python setup
       uses: actions/setup-python@v1
     - name: build
#        run: | 
#            python -m pip install --upgrade pip
#            pip install pylint
#            pylint *.py
     - name: Running lintering
       uses: pyrunit/pylint-action@v1.0.0
       with:
         source: .
         useConda: true
         disable: W1203,C0103

#@Nandak99
 
#        run: cd helloworld && python main.py
#      - name: Python Pylin GitHub Action
#        uses: fylein/python-pylint-github-action@v1
#        with:
#          args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc ./
